#ifndef CONFIG_H
#define CONFIG_H
#include <Arduino.h>

#define FASE_R_HIGH_PIN GPIO_NUM_2
#define FASE_R_LOW_PIN GPIO_NUM_15
#define FASE_S_HIGH_PIN GPIO_NUM_16
#define FASE_S_LOW_PIN GPIO_NUM_4
#define FASE_T_HIGH_PIN GPIO_NUM_5
#define FASE_T_LOW_PIN GPIO_NUM_17
#define POTENTIOMETER_PIN GPIO_NUM_34

#define LUT_SIZE 4096
#define MAX_FREQ 100.0
#define MIN_FREQ 20.0

#endif